name: penjaga_entok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.0.1
  http: ^1.2.2
  image: ^4.9.1
  shared_preferences: ^2.3.2
  timezone: ^0.11.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_entok.png"
