"""Replace weight_logs with unified timbangan and timbangan_readings tables

Revision ID: 39d72db892ce
Revises: 
Create Date: 2026-06-06 21:48:45.144919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d72db892ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.Enum('TANGGUH', 'READY', 'LIMITED', 'NEW', name='catalog_tags'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeds_name'), ['name'], unique=True)

    op.create_table('formulations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('target_consumption', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('composition', sa.JSON(), nullable=False),
    sa.Column('alternative_feeds', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulations_phase'), ['phase'], unique=True)

    op.create_table('population_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('difference', sa.String(length=20), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('populations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('total_ducks', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('populations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_populations_phase'), ['phase'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('schedule_time', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('info_detail', sa.Text(), nullable=True),
    sa.Column('warning_note', sa.Text(), nullable=True),
    sa.Column('general_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timbangan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tipe', sa.Enum('DEDICATED', 'MULTI', name='timbangan_tipe'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='timbangan_status'), nullable=False),
    sa.Column('default_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PENGAWAS', 'PENJAGA', name='user_roles'), nullable=False),
    sa.Column('shift', sa.Enum('PAGI', 'SORE', 'FULL_TIME', name='keeper_shifts'), nullable=True),
    sa.Column('status', sa.Enum('AKTIF', 'NONAKTIF', name='account_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('RESTOCK', 'FORMULASI', 'INVENTARIS', 'SISTEM', name='log_types'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_transactions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('feed_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='transaction_types'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('keeper_id', sa.String(length=50), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keeper_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('thumbnail_img', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timbangan_readings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timbangan_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('feed_id', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timbangan_id'], ['timbangan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timbangan_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timbangan_readings_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_timbangan_readings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timbangan_readings_timbangan_id'), ['timbangan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timbangan_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timbangan_readings_timbangan_id'))
        batch_op.drop_index(batch_op.f('ix_timbangan_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_timbangan_readings_label'))

    op.drop_table('timbangan_readings')
    op.drop_table('task_steps')
    op.drop_table('task_executions')
    op.drop_table('feed_transactions')
    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('timbangan')
    op.drop_table('tasks')
    with op.batch_alter_table('populations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_populations_phase'))

    op.drop_table('populations')
    op.drop_table('population_logs')
    with op.batch_alter_table('formulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulations_phase'))

    op.drop_table('formulations')
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeds_name'))

    op.drop_table('feeds')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
